[package]
name = "actix-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0-beta.19"
serde_json = "1.0"
serde = { version = "1", features = ["derive"] }
validator = { version = "0.12", features = ["derive"] }
derive_more = "0.99"
sqlx = { version = "0.5", default-features = false, features = [ "runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"] }
config = "0.11.0"
argon2 = { version = "0.3", features = ["std"] }
rand_core = { version = "0.6", features = ["std"] }

[dev-dependencies]
actix-rt = "2"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "actix-backend"
