version: "3"
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    networks:
      - internal
    env_file:
      - .env_dev
    environment:
      - PGDATA=/var/lib/postgres/data
    ports:
      - 5432:5432

  redis:
    image: redis:6-alpine
    container_name: redis
    command: redis-server --requirepass password
    networks:
      - internal
    ports:
      - 6379:6379

networks:
  internal:
    driver: bridge
