# Configuration for development

application:
  host: 127.0.0.1
  port: 8000

database:
  host: 127.0.0.1
  port: 5432
  username: postuser
  password: postpass
  database_name: actix
  require_ssl: false

redis:
  host: 127.0.0.1
  port: 6379
  username: default 
  password: redispass

ttl:
  session_token_short: 3600
  session_token_long: 86400 # 30 days
  verification_token: 3600
  password_reset: 3600
  two_fa_enable_timeout: 1800
  two_fa_login_timeout: 1800

email:
  smtp_host: 127.0.0.1
  smtp_port: 1025
  smtp_username: smtpuser
  smtp_password: smtppass
  noreply_email: Actix <noreply@actixapp.local>
